USE master
GO
/*------------------------------------------------------------------------*/
IF EXISTS ( SELECT  name FROM 'sys.databases' WHERE name = N'FolyirNyilv')
ALTER DATABASE FolyirNyilv SET single_user WITH ROLLBACK immediate
DROP DATABASE FolyirNyilv
CREATE DATABASE FolyirNyilv
GO
USE FolyirNyilv
GO
CREATE TABLE dbo.FTORZS(
    FAZON char(4) NOT NULL
    FTIPUS nvarchar(20) NOT NULL CONSTRAINT Params_Ftipus CHECK (FTIPUS in ('napi','családi','szakmai tudományos','egyéb'))
    FCIM nvarchar(50) NOT NULL
    FKIAD nvarchar(50) NOT NULL
    FHDIJ char(6) NOT NULL CONSTRAINT Params_Fhdij CHECK(FHDIJ >= 100 AND FHDIJ < 100000)
    CONSTRAINT PK_FTORZS PRIMARY KEY (FAZON ASC)
)
GO
CREATE TABLE dbo.ETORZS(
    EKOD char(4) NOT NULL
    ENEV nvarchar(50) NOT NULL
    ESZDAT date NOT NULL CONSTRAINT Params_Eszdat CHECK((CONVERT(DATE,GETDATE()) - ESZDAT) >= 18)
    EIRSZ char(4) NOT NULL CONSTRAINT Params_Eirsz CHECK(EIRSZ >= 1011 AND EIRSZ <= 9909)
    ETELEP nvarchar(50) NOT NULL
    EUTCA nvarchar(50) NOT NULL
    CONSTRAINT PK_ETORZS PRIMARY KEY (EKOD ASC)
)
GO
CREATE TABLE dbo.ELOFIZ(
    EKOD char(4) NOT NULL
    EKDATUM date NOT NULL DEFAULT GETDATE()
    EVDATUM date NOT NULL
    FAZON char(4) NOT NULL
    EFIZDB char(4) NOT NULL CONSTRAINT Params_Efizdb CHECK(EFIZDB < 1000 AND EFIZDB > 0))
    ALTER TABLE ELOFIZ ADD CONSTRAINT FK_EKOD FOREIGN KEY (EKOD) REFERENCES ETORZS(EKOD);
    ALTER TABLE ELOFIZ ADD CONSTRAINT FK_FAZON FOREIGN KEY (FAZON) REFERENCES FTORZS(FAZON);
GO