USE master
GO
/*------------------------------------------------------------------------*/
ALTER SERVER ROLE [sysadmin] ADD MEMBER [G14\Daniel]
/*------------------------------------------------------------------------*/
GO
IF EXISTS (
	SELECT name
		FROM sys.databases
		WHERE name = N'FiktivRakt'
)
ALTER DATABASE FiktivRakt SET single_user WITH ROLLBACK immediate
DROP DATABASE FiktivRakt
CREATE DATABASE FiktivRakt
GO
USE FiktivRakt
GO
/*------------------------------------------------------------------------*/
CREATE TABLE dbo.UGYFELEK(
    UGYFEL_ID int IDENTITY(1,1) NOT NULL,
    NEV nvarchar(100) NOT NULL,
    TELEFONSZAM char(12) NOT NULL,
    IRSZAM char(4) NOT NULL,
    TELEPULES nvarchar(50) NOT NULL,
    UTCA nvarchar(50) NOT NULL,
    HAZSZAM varchar(10) NOT NULL,
    CONSTRAINT PK_Ugyfelek PRIMARY KEY (UGYFEL_ID ASC)
)
GO
CREATE TABLE dbo.TERMEKEK(
    TERMEK_ID int IDENTITY(1,1) NOT NULL,
    NEV nvarchar(100) NOT NULL,
    GYARTO_ID char(3) NOT NULL,
    KESZLET bit,
    KORNYEZETBARAT bit,
    KATEGORIA_ID int NOT NULL,
    CONSTRAINT PK_Termekek PRIMARY KEY (TERMEK_ID ASC)
)
GO
CREATE TABLE dbo.UGYINTEZO(
    UGYINTEZO_ID int IDENTITY(1,1) NOT NULL,
    NEV nvarchar(50) NOT NULL,
    CIM nvarchar(50) NOT NULL,
    TELEFONSZAM char(12) NOT NULL,
    CONSTRAINT PK_Ugyintezo PRIMARY KEY (UGYINTEZO_ID ASC)
)
GO
CREATE TABLE dbo.MEGRENDELESEK(
    MEGRENDELES_ID int NOT NULL,
    MEGRENDELES_DATUMA datetime NOT NULL,
    TERMEK_ID int NOT NULL,
    MENNYISEG int,
    FIZETVE bit,
    UGYFEL_ID int NOT NULL,
    UGYINTEZO_ID int NOT NULL,
    CONSTRAINT PK_Megrend PRIMARY KEY (MEGRENDELES_ID ASC))
    ALTER TABLE MEGRENDELESEK ADD CONSTRAINT FK_Termek FOREIGN KEY (TERMEK_ID) REFERENCES TERMEKEK(TERMEK_ID);
    ALTER TABLE MEGRENDELESEK ADD CONSTRAINT FK_Ugyfel FOREIGN KEY (UGYFEL_ID) REFERENCES UGYFELEK(UGYFEL_ID);
    ALTER TABLE MEGRENDELESEK ADD CONSTRAINT FK_Ugyintezo FOREIGN KEY (UGYINTEZO_ID) REFERENCES UGYINTEZO(UGYINTEZO_ID);
GO
CREATE TABLE dbo.KATEGORIAK(
    KATEGORIA_ID int NOT NULL,
    KATEGORIA_NEV nvarchar(100) NOT NULL,
    CONSTRAINT PK_Kateg PRIMARY KEY (KATEGORIA_ID ASC)
	)
GO
CREATE TABLE dbo.GYARTOK(
    GYARTO_ID int NOT NULL,
    GYARTO_NEV nvarchar(100) NOT NULL,
    GYARTO_ORSZAG nvarchar(100) NOT NULL,
    CONSTRAINT PK_Gyarto PRIMARY KEY (GYARTO_ID ASC)
	)
GO